# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=2000
SAVEHIST=10000
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/samuel/.zshrc'
fpath+=~/.zfunc

autoload -Uz compinit
compinit
# End of lines added by compinstall

# === CUSTOM ===
# === I demand to see your Manager! Lol ==>
export ZSH="$HOME/.local/share/sheldon/repos/github.com/ohmyzsh/ohmyzsh"
eval "$(sheldon source)"

# === VARIABLES ===

# Editor Definition
export EDITOR=nvim

# Auto ls-commands
auto-ls-custom_function () {
  ls --color=always
  if [ -d .git ];then
    git status
  fi
}
export AUTO_LS_COMMANDS=(custom_function)

# === COMPLETIONS ===

# === ALIASES ===
alias zshsrc="source ~/.zshrc"
alias zshconf="edit ~/.dotfiles/src/zsh/zshrc"
alias nvimconf="nvim ~/.config/nvim/init.vim"
alias spaceconf="nvim ~/.dotfiles/src/SpaceVim/init.toml"
alias starconf="nvim ~/.dotfiles/src/starship/starship.toml"
alias speedby="speed-test -b"
alias py3="python3"
alias cvenv="virtualenv -p python3 venv"
alias srcenv="source venv/bin/activate"
alias yodl="youtube-dl"
alias bat="batcat"
alias fd="fdfind"
alias ..="cd .."
alias alien="alien-update"
alias ipy="ipython3"
alias flowconf="sudoedit /etc/systemd/user/flowy.service"
# ===================================================================== END
sha256() {
    echo "$1 $2" | sha256sum --check
}

# COMPLETIONS
# PIPENV

#compdef pipenv
_pipenv() {
  eval $(env COMMANDLINE="${words[1,$CURRENT]}" _PIPENV_COMPLETE=complete-zsh  pipenv)
}
if [[ "$(basename ${(%):-%x})" != "_pipenv" ]]; then
  autoload -U compinit && compinit
  compdef _pipenv pipenv
fi
# PIP and PIP3
# pip zsh completion start
function _pip_completion {
  local words cword
  read -Ac words
  read -cn cword
  reply=( $( COMP_WORDS="$words[*]" \
             COMP_CWORD=$(( cword-1 )) \
             PIP_AUTO_COMPLETE=1 $words[1] 2>/dev/null ))
}
compctl -K _pip_completion pip3
# pip zsh completion end


alias ls="ls --color=always"
# Nord Dir Colors
test -r ~/.dir_colors && eval $(dircolors ~/.dir_colors)

eval $(thefuck --alias)
alias fword="fuck"
